image: golang:1.11.4-alpine3.8

build:
  stage: build
  before_script:
    - apk update
    - apk add lftp
  script:
    - go run main.go
    - lftp -c "open -u ${FTP_USER},${FTP_PASS} ${FTP_HOST};mput outputs/*.html;mput outputs/*.xml;cd static/;mrm *;mput outputs/*.js;mput outputs/*.css"
