image: golang:1.11.4-alpine3.8

build:
  stage: build
  before_script:
    - apk update
    - apk add git lftp
    - go get github.com/gomarkdown/markdown
    - go get github.com/gorilla/feeds
    - go get github.com/tdewolff/minify
  script:
    - go run main.go
    - lftp -c "open -u ${FTP_USER},${FTP_PASS} ${FTP_HOST};mput outputs/*.html;mput outputs/*.xml"
