trigger:
  branches:
    include:
      - builder
  paths:
    exclude:
      - README.md
pr:
  branches:
    include:
      - builder
  paths:
    exclude:
      - README.md
pool:
  vmImage: "ubuntu-latest"
variables:
  GOPATH: "$(system.defaultWorkingDirectory)/gopath"
  GOROOT: "/opt/hostedtoolcache/go/1.12.0"
  modulePath: "$(GOPATH)/src/github.com/$(build.repository.name)"
  GO111MODULE: "on"
steps:
  - task: GoTool@0
    inputs:
      version: 1.12
    displayName: "Use Go 1.12"
  - script: |
      mkdir -p '$(GOPATH)/pkg'
      mkdir -p '$(modulePath)'
      shopt -s extglob
      mv !(gopath) $(modulePath)
    displayName: "Setup"
  - task: Go@0
    inputs:
      command: "build"
      arguments: "-mod=vendor -o=generator"
      workingDirectory: "$(modulePath)"
    displayName: "Build website generator"
  - script: "./generator"
    workingDirectory: "$(modulePath)"
    displayName: "Generate website"
  - script: |
      cd '$(modulePath)/dist'
      git init
      git config user.name "Azure Pipelines"
      git config user.email "git@imlonghao.com"
      git add .
      git commit -m "Update"
      git push --force --quiet "https://$(GH_TOKEN)@github.com/imlonghao/imlonghao.com.git" master:master
    condition: not(eq(variables['Build.Reason'], 'PullRequest'))
    displayName: "Deploy website"
