trigger:
  branches:
    include:
      - builder
  paths:
    exclude:
      - README.md
pr:
  branches:
    include:
      - builder
  paths:
    exclude:
      - README.md
pool:
  vmImage: "ubuntu-latest"
variables:
  GOPATH: "$(system.defaultWorkingDirectory)/gopath"
  GOROOT: "/opt/hostedtoolcache/go/1.12.0"
  modulePath: "$(GOPATH)/src/github.com/$(build.repository.name)"
  GO111MODULE: "on"
steps:
  - task: GoTool@0
    inputs:
      version: 1.12
    displayName: "Use Go 1.12"
  - script: |
      mkdir -p '$(GOPATH)/pkg'
      mkdir -p '$(modulePath)'
      shopt -s extglob
      mv !(gopath) $(modulePath)
    displayName: "Setup"
  - task: Go@0
    inputs:
      command: "build"
      arguments: "-mod=vendor -o=generator"
      workingDirectory: "$(modulePath)"
    displayName: "Build website generator"
  - script: "./generator"
    workingDirectory: "$(modulePath)"
    displayName: "Generate website"
  - task: FtpUpload@1
    inputs:
      credentialsOption: "inputs"
      serverUrl: $(FTP_HOST)
      username: $(FTP_USER)
      password: $(FTP_PASS)
      rootDirectory: "$(modulePath)/dist"
      filePatterns: "**"
      remoteDirectory: "/"
      clean: false
      cleanContents: false
      overwrite: true
      preservePaths: true
      trustSSL: true
    condition: not(eq(variables['Build.Reason'], 'PullRequest'))
    displayName: "Deploy website"
