name: imlonghao.com

on: [push, pull_request]

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build website generator
        run: |
          go build -mod=vendor -o=generator
      - name: Generate website
        run: ./generator
      - name: Push website
        if: github.event_name == 'push' && github.ref == 'refs/heads/builder'
        run: |
          cd dist
          git init
          git config user.name "Github Actions"
          git config user.email "git@imlonghao.com"
          git add .
          git commit -m "Update"
          git push --force --quiet "https://${{ secrets.GH_TOKEN }}@github.com/imlonghao/imlonghao.com.git" master:master
      - name: Deploy website
        if: github.event_name == 'push' && github.ref == 'refs/heads/builder'
        run: |
          curl -X POST ${{ secrets.WEBHOOK }}
